### ISSUE TITLE
S3 object not uploaded when using 'interval'

### ISSUE THREAD

**Issue by andrewkroh** [leehinman/spigot#11]
When using the `interval` setting with the S3 output no files are uploaded. This is the config used:

```yaml
runners: 
  - 
    generator: 
      include_timestamp: false
      type: "aws:vpcflow"
    interval: 2s
    output: 
      bucket: filebeat-s3-integtest-o1ahrn
      prefix: spigot/aws/vpcflow/vpcflow
      region: us-east-1
      type: s3
    records: 100000
```

With `interval` the code never reaches the `output.Close()` which triggers the upload. It stays with the ticker's `for` loop.

https://github.com/leehinman/spigot/blob/5355992eb40c4cb5f2e798b7db8b9fbdc9b20cb3/pkg/runner/runner.go#L96-L111
